# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project
group=io.github.thebluetropics
version=0.1.7-beta

# Maven
artifact_name=solid-grass-block

# Mod
mod_id=solid_grass_block

# Minecraft
minecraft_version=1.20.6

# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.97.8+1.20.6

# Mappings
mappings_version=1.20.6+build.3

# Github
github_packages_url=https://maven.pkg.github.com/thebluetropics/solid-grass-block

# Mod Menu
modmenu_version=10.0.0
